<?php

/**
 * @file
 * Default theme implementation to display an iCal event.
 *
 * If you are editing this file, remember that all output lines generated by it
 * must end with DOS-style \r\n line endings, and not Unix-style \n, in order to
 * be compliant with the iCal spec.
 *
 * @see http://tools.ietf.org/html/rfc5545#section-3.1
 *
 * @ingroup themeable
 */
print "BEGIN:VEVENT\r\n";
foreach ($fields as $id => $field):
  if (!empty($field->separator)):
   print $field->separator;
  endif;
  print $field->wrapper_prefix;
  print $field->label_html;
  print $field->content;
  print $field->wrapper_suffix;
  print "\r\n";
endforeach;
print "END:VEVENT\r\n";
