<?php

/**
 * @file
 * Time zone field schema.
 */

/**
* Implements hook_field_schema().
*/
function eventbritefield_field_schema($field) {
  return array(
    'columns' => array(
      'value' => array('type' => 'varchar', 'length' => 10, 'not null' => FALSE, 'sortable' => TRUE, 'description' => 'Eventbrite identifier.'),
    ),
    'indexes' => array(
      'value' => array('value'),
    ),
  );
}