; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.22"

; Modules
projects[addressfield][version] = "1.0-beta4"
projects[scald][version] = "1.0"
projects[ctools][version] = "1.3"
projects[calendar][version] = "3.4"
projects[ckeditor][version] = "1.13"
projects[colorbox][version] = "2.4"
projects[date][version] = "2.6"
projects[entity][version] = "1.1"
projects[entityreference][version] = "1.0"
projects[features][version] = "2.0-rc1"
projects[flickrapi][version] = "1.4"
projects[flickrgallery][version] = "2.2"
projects[fullcalendar][version] = "2.0"
projects[geocoder][version] = "1.2"
projects[geofield][version] = "1.1"
projects[geophp][version] = "1.7"
projects[hybridauth][version] = "2.7"
projects[imce][version] = "1.7"
projects[leaflet][version] = "1.0-beta3"
projects[leaflet_more_maps][version] = "1.5"
projects[leaflet_markercluster][version] = "1.0-beta1"
projects[libraries][version] = "2.1"
projects[link][version] = "1.1"
projects[merci][version] = "2.0"
projects[merci_email][version] = "1.0-beta2"
projects[oauth][version] = "3.1"
projects[pathauto][version] = "1.2"
projects[pdf][version] = "1.2"
projects[registration][version] = "1.2"
projects[services][version] = "3.4"
projects[rules][version] = "2.3"
projects[rules_forms][version] = "1.0-rc2"
projects[scald_file][version] = "1.0-beta2"
projects[scald_flickr][version] = "1.1"
projects[scald_pdf][version] = "1.2"
projects[scald_twitter][version] = "1.0-rc1"
projects[services_views][version] = "1.0-beta2"
projects[sharethis][version] = "2.5"
projects[social_media_links][version] = "1.x-dev"
projects[superfish][version] = "1.9"
projects[tagclouds][version] = "1.9"
projects[token][version] = "1.5"
projects[views][version] = "3.7"

; Themes
projects[rubik][version] = "4.0-beta8"
projects[skeletontheme][version] = "1.2"
projects[tao][version] = "3.0-beta4"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = ""
libraries[ckeditor][download][url] = ""
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[colorbox][download][type] = ""
libraries[colorbox][download][url] = ""
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[fullcalendar][download][type] = ""
libraries[fullcalendar][download][url] = ""
libraries[fullcalendar][directory_name] = "fullcalendar"
libraries[fullcalendar][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[hybridauth][download][type] = ""
libraries[hybridauth][download][url] = ""
libraries[hybridauth][directory_name] = "hybridauth"
libraries[hybridauth][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[hybridauth-additional-providers-1.8][download][type] = ""
libraries[hybridauth-additional-providers-1.8][download][url] = ""
libraries[hybridauth-additional-providers-1.8][directory_name] = "hybridauth-additional-providers-1.8"
libraries[hybridauth-additional-providers-1.8][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[leaflet][download][type] = ""
libraries[leaflet][download][url] = ""
libraries[leaflet][directory_name] = "leaflet"
libraries[leaflet][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[leaflet_markercluster][download][type] = ""
libraries[leaflet_markercluster][download][url] = ""
libraries[leaflet_markercluster][directory_name] = "leaflet_markercluster"
libraries[leaflet_markercluster][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[superfish][download][type] = ""
libraries[superfish][download][url] = ""
libraries[superfish][directory_name] = "superfish"
libraries[superfish][type] = "library"

