; FabDrupal 7.x-0.1
; A Drupal distribution for FabLabs

; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.22"

; Modules ================================================================================

projects[addressfield][version] = "1.0-beta4"
projects[scald][version] = "1.0"
projects[ctools][version] = "1.3"
projects[calendar][version] = "3.4"
projects[ckeditor][version] = "1.13"
projects[colorbox][version] = "2.4"
projects[date][version] = "2.6"
projects[entity][version] = "1.2"
projects[entityreference][version] = "1.0"
projects[features][version] = "2.0-rc3"
projects[flickrapi][version] = "1.4"
projects[flickrgallery][version] = "2.2"
projects[fullcalendar][version] = "2.0"
projects[geocoder][version] = "1.2"
projects[geofield][version] = "1.1"
projects[geophp][version] = "1.7"
projects[hybridauth][version] = "2.7"
projects[imce][version] = "1.7"
projects[leaflet][version] = "1.0-beta3"
projects[leaflet_more_maps][version] = "1.5"
projects[leaflet_markercluster][version] = "1.0-beta1"
projects[libraries][version] = "2.1"
projects[link][version] = "1.1"
projects[merci][version] = "2.0"
projects[merci_email][version] = "1.0-beta2"
projects[oauth][version] = "3.1"
projects[pathauto][version] = "1.2"
projects[pdf][version] = "1.2"
projects[registration][version] = "1.2"
projects[services][version] = "3.4"
projects[rules][version] = "2.3"
projects[rules_forms][version] = "1.0-rc2"
projects[scald_file][version] = "1.0-beta2"
projects[scald_flickr][version] = "1.1"
projects[scald_pdf][version] = "1.2"
projects[scald_twitter][version] = "1.0-rc1"
projects[services_views][version] = "1.0-beta2"
projects[sharethis][version] = "2.5"
projects[social_media_links][version] = "1.x-dev"
projects[superfish][version] = "1.9"
projects[tagclouds][version] = "1.9"
projects[token][version] = "1.5"
projects[views][version] = "3.7"

; Features ===============================================================================

projects[content_types][type] = "module"
projects[content_types][subdir] = "fabdrupal"
projects[content_types][download][type] = "get"
projects[content_types][download][url] = "https://github.com/OpenP2PDesignOrg/FabDrupalDevelopment/raw/master/features/content_types-7.x-0.1.tar"
;projects[content_types][version] = "7.x-0.1"

projects[event_registration][type] = "module"
projects[event_registration][subdir] = "fabdrupal"
projects[event_registration][download][type] = "get"
projects[event_registration][download][url] = "https://github.com/OpenP2PDesignOrg/FabDrupalDevelopment/raw/master/features/event_registration-7.x-0.1.tar"
;projects[event_registration][version] = "7.x-0.1"

projects[fabdrupal_blog][type] = "module"
projects[fabdrupal_blog][subdir] = "fabdrupal"
projects[fabdrupal_blog][download][type] = "get"
projects[fabdrupal_blog][download][url] = "https://github.com/OpenP2PDesignOrg/FabDrupalDevelopment/raw/master/features/fabdrupal_blog-7.x-0.1.tar"
;projects[fabdrupal_blog][version] = "7.x-0.1"

projects[machine_reservation][type] = "module"
projects[machine_reservation][subdir] = "fabdrupal"
projects[machine_reservation][download][type] = "get"
projects[machine_reservation][download][url] = "https://github.com/OpenP2PDesignOrg/FabDrupalDevelopment/raw/master/features/machine_reservation-7.x-0.1.tar"
;projects[machine_reservation][version] = "7.x-0.1"

projects[open_api][type] = "module"
projects[open_api][subdir] = "fabdrupal"
projects[open_api][download][type] = "get"
projects[open_api][download][url] = "https://github.com/OpenP2PDesignOrg/FabDrupalDevelopment/raw/master/features/open_api-7.x-0.1.tar"
;projects[open_api][version] = "7.x-0.1"

projects[various_settings][type] = "module"
projects[various_settings][subdir] = "fabdrupal"
projects[various_settings][download][type] = "get"
projects[various_settings][download][url] = "https://github.com/OpenP2PDesignOrg/FabDrupalDevelopment/raw/master/features/various_settings-7.x-0.1.tar"
;projects[various_settings][version] = "7.x-0.1"


; Themes =================================================================================

projects[rubik][version] = "4.0-beta8"
projects[skeletontheme][version] = "1.2"
projects[tao][version] = "3.0-beta4"

; Libraries ==============================================================================

libraries[ckeditor][download][type] = "get"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor/CKEditor/CKEditor%204.2.1/ckeditor_4.2.1_full.zip"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

libraries[colorbox][download][type] = "get"
libraries[colorbox][download][url] = "https://github.com/jackmoore/colorbox/archive/1.x.zip"
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"

libraries[fullcalendar][download][type] = "get"
libraries[fullcalendar][download][url] = "https://github.com/arshaw/fullcalendar/releases/download/v1.6.4/fullcalendar-1.6.4.zip"
libraries[fullcalendar][directory_name] = "fullcalendar"
libraries[fullcalendar][type] = "library"

libraries[hybridauth][download][type] = "get"
libraries[hybridauth][download][url] = "http://downloads.sourceforge.net/project/hybridauth/hybridauth-2.1.2.zip?r=&ts=1380232726&use_mirror=heanet"
libraries[hybridauth][directory_name] = "hybridauth"
libraries[hybridauth][type] = "library"

libraries[hybridauth-additional-providers-1.8][download][type] = "get"
libraries[hybridauth-additional-providers-1.8][download][url] = "http://downloads.sourceforge.net/project/hybridauth/hybridauth-additional-providers-1.8.zip?r=http%3A%2F%2Fhybridauth.sourceforge.net%2Fdownload.html&ts=1380232759&use_mirror=switch"
libraries[hybridauth-additional-providers-1.8][directory_name] = "hybridauth-additional-providers-1.8"
libraries[hybridauth-additional-providers-1.8][type] = "library"

libraries[leaflet][download][type] = "get"
libraries[leaflet][download][url] = "http://leaflet-cdn.s3.amazonaws.com/build/leaflet-0.6.4.zip"
libraries[leaflet][directory_name] = "leaflet"
libraries[leaflet][type] = "library"

libraries[leaflet_markercluster][download][type] = "get"
libraries[leaflet_markercluster][download][url] = "https://github.com/Leaflet/Leaflet.markercluster/archive/master.zip"
libraries[leaflet_markercluster][directory_name] = "leaflet_markercluster"
libraries[leaflet_markercluster][type] = "library"

libraries[superfish][download][type] = "get"
libraries[superfish][download][url] = "https://github.com/mehrpadin/Superfish-for-Drupal/archive/1.x.zip"
libraries[superfish][directory_name] = "superfish"
libraries[superfish][type] = "library"

