<?php

/**
 * Implements hook_library().
 */
function leaflet_markercluster_library() {

  if (!($path = leaflet_markercluster_get_library_path())) {
    return NULL;
  }
  $libraries['leaflet_markercluster'] = array(
    'title' => 'Leaflet Markercluster',
    'version' => 0, // we don't have a version
    'js' => array(
      array(
        'type' => 'file',
        'data' => "$path/leaflet.markercluster.js",
        'group' => JS_LIBRARY,
        'preprocess' => FALSE,
      ),
    ),
    'css' => array(
      "$path/MarkerCluster.css" => array(
        'type' => 'file',
        'media' => 'screen',
      ),
      "$path/MarkerCluster.Default.css" => array(
        'type' => 'file',
        'media' => 'screen',
      ),
    ),
  );

  return $libraries;
}

function leaflet_markercluster_preprocess_leaflet_map(&$vars) {
  drupal_add_library('leaflet_markercluster', 'leaflet_markercluster');
  drupal_add_js(drupal_get_path('module', 'leaflet_markercluster') . '/leaflet_markercluster.drupal.js');
}


/**
 * Implements hook_requirements().
 */
function leaflet_markercluster_requirements($phase) {

  if ($phase != 'runtime') {
    return array();
  }
  $requirements['leaflet_markercluster']['title'] = t('Leaflet MarkerCluster library');
  if ($path = leaflet_markercluster_get_library_path()) {
    $file = "$path/leaflet.markercluster.js";
  }
  if ($path && file_exists($file)) {
    $requirements['leaflet_markercluster']['value'] = t('Installed');
    $requirements['leaflet_markercluster']['severity'] = REQUIREMENT_OK;
  }
  else {
    $requirements['leaflet_markercluster']['value'] =
      $path ? t('File not found: %file', array('%file' => $file)) : t('/leaflet_markercluster library directory missing');
    $requirements['leaflet_markercluster']['severity'] = REQUIREMENT_ERROR;
  }

  return $requirements;
}

function leaflet_markercluster_get_library_path() {
  $path = libraries_get_path('leaflet_markercluster');
  return $path ? "$path/dist" : FALSE;
}
